class Artifacts:
    instances = []  # Class variable to store all Browser instances

    def __init__(self, name, category, time=False, exist=False, atime=None, mtime=None, ctime=None, check=False):
        self.check = check
        self.exist = exist
        self.name = name
        self.category = category
        self.time = time
        self.atime = atime
        self.mtime = mtime
        self.ctime = ctime
 

        # Append this instance to the class variable Artifacts
        Artifacts.instances.append(self)

    def __repr__(self):
        return (f"Artifacts(name={self.name}, category={self.category}, "
                f"check={self.check}, exist={self.exist})")
    

# Category == Antivirus --------------------------------------------------------------------------------------------------
ALYac = Artifacts(name="ALYac", category="Antivirus")
Avast = Artifacts(name="Avast", category="Antivirus")
AVG = Artifacts(name="AVG", category="Antivirus")
Avira = Artifacts(name="Avira", category="Antivirus")
BitDefender = Artifacts(name="BitDefender", category="Antivirus")
Cybereason = Artifacts(name="Cybereason", category="Antivirus")
Emsisoft = Artifacts(name="Emsisoft", category="Antivirus")
ESET = Artifacts(name="ESET", category="Antivirus")
FSecure = Artifacts(name="FSecure", category="Antivirus")
HitmanPro = Artifacts(name="HitmanPro", category="Antivirus")
Malwarebytes = Artifacts(name="Malwarebytes", category="Antivirus")
McAfee = Artifacts(name="McAfee", category="Antivirus")
RougeKiller = Artifacts(name="RougeKiller", category="Antivirus")
SecureAge = Artifacts(name="SecureAge", category="Antivirus")
SentinelOne = Artifacts(name="SentinelOne", category="Antivirus")
Sophos = Artifacts(name="Sophos", category="Antivirus")
SUPERAntiSpyware = Artifacts(name="SUPERAntiSpyware", category="Antivirus")
SymantecAV = Artifacts(name="SymantecAV", category="Antivirus")
TotalAV = Artifacts(name="TotalAV", category="Antivirus")
TrendMicro = Artifacts(name="TrendMicro", category="Antivirus")
V3Lite = Artifacts(name="V3Lite", category="Antivirus")
VIPRE = Artifacts(name="VIPRE", category="Antivirus")
Webroot = Artifacts(name="Webroot", category="Antivirus")
WindowsDefender = Artifacts(name="WindowsDefender", category="Antivirus")


# Category == Apps --------------------------------------------------------------------------------------------------
OnePassword = Artifacts(name="1Password", category="Apps")
FKVideoDownloader = Artifacts(name="4KVideoDownloader", category="Apps")
Sevenzip = Artifacts(name="7Zip", category="Apps")
AceText= Artifacts(name="AceText", category="Apps")
AcronisTrueImage = Artifacts(name="AcronisTrueImage", category="Apps")
ALZip = Artifacts(name="ALZip", category="Apps")
Ammyy = Artifacts(name="Ammyy", category="Apps")
AnyDesk = Artifacts(name="AnyDesk", category="Apps")
AsperaConnect = Artifacts(name="AsperaConnect", category="Apps")
AteraAgent = Artifacts(name="AteraAgent", category="Apps")
Bandizip = Artifacts(name="Bandizip", category="Apps")
BoxDrive = Artifacts(name="BoxDrive", category="Apps")
CiscoJabber = Artifacts(name="CiscoJabber", category="Apps")
ClipboardMaster = Artifacts(name="ClipboardMaster", category="Apps")
Confluence = Artifacts(name="Confluence", category="Apps")
DaumCafe = Artifacts(name="DaumCafe", category="Apps")
DirectoryOpus = Artifacts(name="DirectoryOpus", category="Apps")
Discord = Artifacts(name="Discord", category="Apps")
DoubleCommander = Artifacts(name="DoubleCommander", category="Apps")
Dropbox = Artifacts(name="Dropbox", category="Apps")
EFCommander = Artifacts(name="EFCommander", category="Apps")
Evernote = Artifacts(name="Evernote", category="Apps")
Everything = Artifacts(name="Everything", category="Apps")
ExchangeClientAccess = Artifacts(name="ExchangeClientAccess", category="Apps")
Fences = Artifacts(name="Fences", category="Apps")
FileZilaClient = Artifacts(name="FileZilaClient", category="Apps")
FileZilaServer = Artifacts(name="FileZilaServer", category="Apps")
FreeCommander = Artifacts(name= "FreeCommander", category="Apps")
FreeDownloadManager = Artifacts(name="FreeDownloadManager", category="Apps")
FreeFileSync = Artifacts(name="FreeFileSync", category="Apps")
GoogleDrive = Artifacts(name="GoogleDrive", category="Apps")
GoogleEarth = Artifacts(name="GoogleEarth", category="Apps")
HeidiSQL = Artifacts(name="HeidiSQL", category="Apps")
HexChat = Artifacts(name="HexChat", category="Apps")
IceChat = Artifacts(name="IceChat", category="Apps")
IrfanView = Artifacts(name="IrfanView", category="Apps")
iTunesBackup = Artifacts(name="iTunesBackup", category="Apps")
JavaWebCache = Artifacts(name="JavaWebCache", category="Apps")
JDownloader2 = Artifacts(name="JDownloader2", category="Apps")
KakaoTalk = Artifacts(name="KakaoTalk", category="Apps")
Kaseya = Artifacts(name="Kaseya", category="Apps")
LINE = Artifacts(name="Line", category="Apps")
LogMeIn = Artifacts(name="LogMeIn", category="Apps")
MacriumReflect = Artifacts(name="MacriumReflect", category="Apps")
Mattermost = Artifacts(name="Mattermost", category="Apps")
MediaMonkey = Artifacts(name="MediaMonkey", category="Apps")
Melon = Artifacts(name="Melon", category="Apps")
MicrosoftOneNote = Artifacts(name="MicrosoftOneNote", category="Apps")
MicrosoftStickyNotes = Artifacts(name="MicrosoftStickyNotes", category="Apps")
MicrosoftTeams = Artifacts(name="MicrosoftTeams", category="Apps")
MicrosoftToDo = Artifacts(name="MicrosoftToDo", category="Apps")
MidnightCommander = Artifacts(name="MidnightCommander", category="Apps")
mIRC = Artifacts(name="mIRC", category="Apps")
mRemoteNG = Artifacts(name="mRemoteNG", category="Apps")
MultiCommander = Artifacts(name="MultiCommander", category="Apps")
NaverBand = Artifacts(name="NaverBand", category="Apps")
NaverCafe = Artifacts(name="NaverCafe", category="Apps")
Nessus = Artifacts(name="Nessus", category="Apps")
Notepad = Artifacts(name="Notepad++", category="Apps")
Notion = Artifacts(name="Notion", category="Apps")
OneCommander = Artifacts(name="OneCommander", category="Apps")
OneDrive = Artifacts(name="OneDrive", category="Apps")
OpenSSHClient = Artifacts(name="OpenSSHClient", category="Apps")
OpenSSHServer = Artifacts(name="OpenSSHServer", category="Apps")
OpenVPNClient = Artifacts(name="OpenVPNClient", category="Apps")
OutlookPSTOST = Artifacts(name="OutlookPSTOST", category="Apps")
Parsec = Artifacts(name="Parsec", category="Apps")
pCloudDatabase = Artifacts(name="pCloudDatabase", category="Apps")
PeaZip = Artifacts(name="PeaZip", category="Apps")
ProtonVPN = Artifacts(name="ProtonVPN", category="Apps")
QDir = Artifacts(name="Q-Dir", category="Apps")
QFinderPro = Artifacts(name="QFinderPro", category="Apps")
Radmin = Artifacts(name="Radmin", category="Apps")
REmoteUtilities = Artifacts(name="REmoteUtilities", category="Apps")
RemoteView = Artifacts(name="RemoteView", category="Apps")
SamsungRemote = Artifacts(name="SamsungRemote", category="Apps")
ScreenConnect = Artifacts(name="ScreenConnect", category="Apps")
ShareX = Artifacts(name="ShareX", category="Apps")
SiemensTIA = Artifacts(name="SiemensTIA", category="Apps")
Signal = Artifacts(name="Signal", category="Apps")
Skype = Artifacts(name="Skype", category="Apps")
Slack = Artifacts(name="Slack", category="Apps")
Snagit = Artifacts(name="Snagit", category="Apps")
SpeedCommander = Artifacts(name="SppedCommander", category="Apps")
Splashtop = Artifacts(name="Splashtop", category="Apps")
Spotify = Artifacts(name="Spotify", category="Apps")
SublimeText = Artifacts(name="SublimeText", category="Apps")
SugarSync = Artifacts(name="SugarSync", category="Apps")
SumatraPDF = Artifacts(name="SumatraPDF", category="Apps")
SupremoRemoteDesktop = Artifacts(name="SupremoRemoteDesktop", category="Apps")
TablacusExplorer = Artifacts(name="TablacusExplorer", category="Apps")
TeamViewer = Artifacts(name="TeamViewer", category="Apps")
Telegram = Artifacts(name="Telegram", category="Apps")
TeraCopy = Artifacts(name="TeraCopy", category="Apps")
Thunderbird = Artifacts(name="Thunderbird", category="Apps")
TotalCommander = Artifacts(name="TotalCommander", category="Apps")
Tox = Artifacts(name="Tox", category="Apps")
TreeSize = Artifacts(name="TreeSize", category="Apps")
Ultraviewer = Artifacts(name="Ultraviewer", category="Apps")
Viber = Artifacts(name="Viber", category="Apps")
VirtualBox = Artifacts(name="VirtualBox", category="Apps")
VLCMediaPlayer = Artifacts(name="VLC Media Player", category="Apps")
VMwareInventory = Artifacts(name="VMwareInven", category="Apps")
VMwareDir = Artifacts(name="VMwareDir", category="Apps")
VNC = Artifacts(name="VNC", category="Apps")
WhatsApp = Artifacts(name="WhatsApp", category="Apps")
WindowsYourPhone = Artifacts(name="WindowsYourPhone", category="Apps")
WinSCP = Artifacts(name="WinSCP", category="Apps")
WireShark = Artifacts(name="WireShark", category="Apps")
XYplorer = Artifacts(name="XYplorer", category="Apps")
Zoom = Artifacts(name="Zoom", category="Apps")


# Category == Browser --------------------------------------------------------------------------------------------------
AvastBrowser = Artifacts(name="AvastBrowser", category="Browser")
Brave = Artifacts(name="Brave", category="Browser")
Chrome = Artifacts(name="Chrome", category="Browser")
Edge = Artifacts(name="Edge", category="Browser")
Firefox = Artifacts(name="Firefox", category="Browser")
InternetExplorer = Artifacts(name="InternetExplorer", category="Browser")
Opera = Artifacts(name="Opera", category="Browser")
PuffinSecureBrowser = Artifacts(name="PuffinSecureBrowser", category="Browser")
Whale = Artifacts(name="Whale", category="Browser")

# Category == Logs --------------------------------------------------------------------------------------------------
ApacheLogFiles = Artifacts(name = "ApacheLogFiles", category="Logs")
ExchangeTransport = Artifacts(name = "ExchangeTransport", category="Logs")
IISLogFiles = Artifacts(name = "IISLogFiles", category="Logs")
ManageEngineLogs = Artifacts(name = "ManageEngineLogs", category="Logs")
MSSQLLog = Artifacts(name = "MSSQLLog", category="Logs")
nginxLogs = Artifacts(name = "nginxLogs", category="Logs")
PowerShellConsoleLog = Artifacts(name = "PowerShellConsoleLog", category="Logs")


# Category == P2P --------------------------------------------------------------------------------------------------
BitTorrent = Artifacts(name = "BitTorrent", category="P2P")
DC = Artifacts(name = "DC++", category="P2P")
Freenet = Artifacts(name = "Freenet", category="P2P")
FrostWire = Artifacts(name = "FrostWire", category="P2P")
Gigatribe = Artifacts(name = "Gigatribe", category="P2P")
NewsbinPro = Artifacts(name = "NewsbinPro", category="P2P")
Newsleecher = Artifacts(name = "Newsleecher", category="P2P")
Nicotine =Artifacts(name = "Nicotine++", category="P2P")
NZBGet = Artifacts(name = "NZBGet", category="P2P")
qBitTorrent = Artifacts(name = "qBitTorrent", category="P2P")
SABnbzd = Artifacts(name = "SABnbzd", category="P2P")
Sharezaz = Artifacts(name = "Sharezaz", category="P2P")
Soulseek = Artifacts(name = "Soulseek", category="P2P")
uTorrent = Artifacts(name = "uTorrent", category="P2P")

# Category == Windows --------------------------------------------------------------------------------------------------
Boot = Artifacts(name = "$Boot", category="Windows", time=True, exist=True)
J = Artifacts(name = "$J", category="Windows", time=True, exist=True)
LogFile = Artifacts(name = "$LogFile", category="Windows", time=True, exist=True)
MFT = Artifacts(name = "$MFT", category="Windows", time=True, exist=True)
MFTMirr = Artifacts(name = "$MFTMirr", category="Windows", time=True, exist=True)
SDS = Artifacts(name = "$SDS", category="Windows", time=True, exist=True)
T = Artifacts(name = "$T", category ="Windows", time=True, exist=True)
amcache = Artifacts(name = "amcache", category="Windows")
AssetAdvisorLog = Artifacts(name = "AssetAdvisorLog", category="Windows")
BCD = Artifacts(name = "BCD", category="Windows")
BITS = Artifacts(name = "BITS", category="Windows")
CertUtil = Artifacts(name = "CertUtil", category="Windows")
EventLog = Artifacts(name = "EventLog", category="Windows")
EventTraceLogs = Artifacts(name = "EventTraceLogs", category="Windows")
EventTranscriptDB = Artifacts(name = "EventTranscriptDB", category="Windows")
GroupPolicy = Artifacts(name = "GroupPolicy", category="Windows")
LNKFilesAndJumpLists = Artifacts(name = "LNKFilesAndJumpLists", category="Windows")
MemoryFiles = Artifacts(name = "MemoryFiles", category="Windows")
MOF = Artifacts(name = "MOF", category="Windows")
OfficeAutosave = Artifacts(name = "OfficeAutosave", category="Windows")
OfficeDiagnostics = Artifacts(name = "OfficeDiagnostics", category="Windows")
OfficeDocumentCache = Artifacts(name = "OfficeDocumentCache", category="Windows")
PCA = Artifacts(name = "PCA", category="Windows")
Prefetch = Artifacts(name = "Prefetch", category="Windows")
RDPCache = Artifacts(name = "RDPCache", category="Windows")
RecentFileCache = Artifacts(name = "RecentFileCache", category="Windows")
RecycleBin = Artifacts(name = "RecycleBin", category="Windows")
RegistryHives = Artifacts(name = "RegistryHives", category="Windows")
ScheduledTasks = Artifacts(name = "ScheduledTasks", category="Windows")
SDB = Artifacts(name = "SDB", category="Windows")
SignatureCatalog = Artifacts(name = "SignatureCatalog", category="Windows")
SnipAndSketch = Artifacts(name = "SnipAndSketch", category="Windows")
SRUM = Artifacts(name = "SRUM", category="Windows")
StartipFolders = Artifacts(name = "StartipFolders", category="Windows")
StartupInfo = Artifacts(name = "StartupInfo", category="Windows")
SUM = Artifacts(name = "SUM", category="Windows")
Syscache = Artifacts(name = "Syscache", category="Windows")
ThumbCache = Artifacts(name = "ThumbCache", category="Windows")
USBDevicesLogs = Artifacts(name = "USBDevicesLogs", category="Windows")
WBEM = Artifacts(name = "WBEM", category="Windows")
WER = Artifacts(name = "WER", category="Windows")
WindowsFirewall = Artifacts(name = "WindowsFirewall", category="Windows")
WindowsIndexSearch = Artifacts(name = "WindowsIndexSearch", category="Windows")
WindowsNotificationsDB = Artifacts(name = "WindowsNotificationsDB", category="Windows")
WindowsOSUpgradeArtifacts = Artifacts(name = "WindowsOSUpgradeArtifacts", category="Windows")
WindowsPowerDiagnostics = Artifacts(name = "WindowsPowerDiagnostics", category="Windows")
WindowsTelemetryDiagnosticsLegacy = Artifacts(name = "WindowsTelemetryDiagnosticsLegacy", category="Windows")
WindowsTimeline = Artifacts(name = "WindowsTimeline", category="Windows")

# Category == WSA --------------------------------------------------------------------------------------------------
WSA = Artifacts(name = "WSA", category="WSA")

# Category == WSL --------------------------------------------------------------------------------------------------
Debian = Artifacts(name = "Debian", category="WSL")
Kali = Artifacts(name = "Kali", category="WSL")
openSUSE = Artifacts(name = "openSUSE", category="WSL")
OracleLinux = Artifacts(name = "OracleLinux", category="WSL")
SUSELinuxEnterpriseServer = Artifacts(name = "SUSELinuxEnterpriseServer", category="WSL")
Ubuntu = Artifacts(name = "Ubuntu", category="WSL")
